package main;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import org.testng.annotations.*;

import static org.testng.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriverService;
import org.openqa.selenium.support.ui.Select;

public class Product_index {
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  public Product_index(WebDriver driver) {
	// TODO Auto-generated constructor stub
	  this.driver = driver;
}

  public void testProductIndex() throws Exception {
    this.driver.get("http://shop.51maike.com.cn/shop/");
    //this.driver.findElement(By.cssSelector("div.nav-title")).click();
    this.driver.findElement(By.xpath("//div[text()=\"商品管理\"]")).click();
    this.driver.findElement(By.xpath("//li[2]/a/div")).click();
    this.driver.findElement(By.id("addProduct")).click();
    this.driver.findElement(By.id("item_2")).click();
    this.driver.findElement(By.id("next")).click();
    this.driver.findElement(By.id("productName")).clear();
    this.driver.findElement(By.id("productName")).sendKeys("回归测试case");
    this.driver.findElement(By.id("shortDes")).clear();
    this.driver.findElement(By.id("shortDes")).sendKeys("回归测试case");
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.id("productCode")).clear();
    this.driver.findElement(By.id("productCode")).sendKeys("000212");
    this.driver.findElement(By.id("addSpec")).click();
    this.driver.findElement(By.xpath("//button[@onclick='openSelSpecWindow(this);']")).click();
    this.driver.findElement(By.xpath("//div[@id='addSkuWindow']/div/div/fieldset/div/div/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.id("toAddSku")).click();
    this.driver.findElement(By.xpath("//button[@onclick='openSelSpecWindow(this);']")).click();
    this.driver.findElement(By.xpath("//div[@id='addSkuWindow']/div/div/fieldset/div/div/span/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.id("toAddSku")).click();
    this.driver.findElement(By.linkText("+添加")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("//button[@onclick='closeSkuValue();']")).click();
    this.driver.findElement(By.cssSelector("div.delSpec > img")).click();
    this.driver.findElement(By.id("addSpec")).click();
    this.driver.findElement(By.xpath("//button[@onclick='openSelSpecWindow(this);']")).click();
    this.driver.findElement(By.xpath("//div[@id='addSkuWindow']/div/div/fieldset/div/div/span/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.id("toAddSku")).click();
    this.driver.findElement(By.linkText("+添加")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div/span/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.id("addSpecV_1")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.id("addSpec")).click();
    this.driver.findElement(By.xpath("(//button[@onclick='openSelSpecWindow(this);'])[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='addSkuWindow']/div/div/fieldset/div/div/span/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.id("toAddSku")).click();
    this.driver.findElement(By.cssSelector("#addSpecV_2 > a.link-primary.noEdit")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).clear();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).sendKeys("红");
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.cssSelector("#addSpecV_2 > a.link-primary.noEdit")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).clear();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).sendKeys("黄");
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.cssSelector("#addSpecV_2 > a.link-primary.noEdit")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[55]")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[55]")).clear();
    this.driver.findElement(By.xpath("(//input[@type='text'])[55]")).sendKeys("红色");
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.xpath("//div[@id='specD_2']/div[2]/div[2]/img")).click();
    this.driver.findElement(By.cssSelector("#specD_2 > div.specV > div.delspecV > img")).click();
    this.driver.findElement(By.cssSelector("#addSpecV_2 > a.link-primary.noEdit")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[2]")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).click();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).clear();
    this.driver.findElement(By.xpath("(//input[@type='text'])[39]")).sendKeys("黄色");
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.cssSelector("#addSpecV_2 > a.link-primary.noEdit")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.id("batch_quto")).click();
    this.driver.findElement(By.id("batch_quto")).clear();
    this.driver.findElement(By.id("batch_quto")).sendKeys("122");
    this.driver.findElement(By.id("quto_yes")).click();
    this.driver.findElement(By.id("batch_sale")).click();
    this.driver.findElement(By.id("batch_sale")).clear();
    this.driver.findElement(By.id("batch_sale")).sendKeys("0.12");
    this.driver.findElement(By.id("sale_yes")).click();
    this.driver.findElement(By.id("batch_inventory")).clear();
    this.driver.findElement(By.id("batch_inventory")).sendKeys("021");
    this.driver.findElement(By.id("inventory_yes")).click();
    this.driver.findElement(By.id("batch_skuCode")).clear();
    this.driver.findElement(By.id("batch_skuCode")).sendKeys("21214");
    this.driver.findElement(By.id("code_yes")).click();
    this.driver.findElement(By.id("skuCode_1367_1255")).clear();
    this.driver.findElement(By.id("skuCode_1367_1255")).sendKeys("21214A");
    this.driver.findElement(By.id("skuCode_1367_1542")).clear();
    this.driver.findElement(By.id("skuCode_1367_1542")).sendKeys("21214B");
    this.driver.findElement(By.id("skuCode_1367_1371")).clear();
    this.driver.findElement(By.id("skuCode_1367_1371")).sendKeys("21214C");
    this.driver.findElement(By.id("skuCode_1369_1255")).clear();
    this.driver.findElement(By.id("skuCode_1369_1255")).sendKeys("21214D");
    this.driver.findElement(By.id("skuCode_1369_1542")).clear();
    this.driver.findElement(By.id("skuCode_1369_1542")).sendKeys("21214E");
    this.driver.findElement(By.id("skuCode_1369_1371")).clear();
    this.driver.findElement(By.id("skuCode_1369_1371")).sendKeys("21214F");
    this.driver.findElement(By.id("chkSkuImg")).click();
    this.driver.findElement(By.cssSelector("label.checkbox-inline")).click();
    this.driver.findElement(By.cssSelector("div.col-sm-2 > button.btn.btn-default")).click();
    this.driver.findElement(By.id("1075_fileCount")).click();
    this.driver.findElement(By.cssSelector("a[title=\"238a65cb90feab1a6c5ec426f46d13ef.jpg\"] > img")).click();
    this.driver.findElement(By.id("saveProductImage")).click();
    this.driver.findElement(By.xpath("//button[@onclick=\"openImgSpace('skuImg_1369',1);\"]")).click();
    this.driver.findElement(By.cssSelector("a[title=\"294bcb65e3577f6cf7dec72d55a26ecd.jpg\"] > img")).click();
    this.driver.findElement(By.id("saveProductImage")).click();
    this.driver.findElement(By.id("displaySoldQty")).click();
    this.driver.findElement(By.id("displayInventory")).click();
    this.driver.findElement(By.cssSelector("div.clearfix > button.btn.btn-default")).click();
    this.driver.findElement(By.cssSelector("a[title=\"294bcb65e3577f6cf7dec72d55a26ecd.jpg\"] > img")).click();
    this.driver.findElement(By.id("saveProductImage")).click();
    this.driver.findElement(By.id("shareTitle")).clear();
    this.driver.findElement(By.id("shareTitle")).sendKeys("分享");
    this.driver.findElement(By.id("shareContent")).clear();
    this.driver.findElement(By.id("shareContent")).sendKeys("这款衣服还可以，分享给你！");
    this.driver.findElement(By.xpath("//button[@onclick=\"openImgSpace('squareShow',5);\"]")).click();
    this.driver.findElement(By.cssSelector("a[title=\"238a65cb90feab1a6c5ec426f46d13ef.jpg\"] > img")).click();
    this.driver.findElement(By.cssSelector("a[title=\"294bcb65e3577f6cf7dec72d55a26ecd.jpg\"] > img")).click();
    this.driver.findElement(By.cssSelector("a[title=\"295fea6f68f6cf0d0292c12eef613a88.jpg\"] > img")).click();
    this.driver.findElement(By.cssSelector("a[title=\"171b3cde42eda4f810fbcccac8c0f81c.jpg\"] > img")).click();
    this.driver.findElement(By.id("saveProductImage")).click();
    this.driver.findElement(By.xpath("//button[@onclick=\"openImgSpace('rectangleShow',1);\"]")).click();
    this.driver.findElement(By.id("1077_fileCount")).click();
    this.driver.findElement(By.cssSelector("a[title=\"Img01.jpg\"] > img")).click();
    this.driver.findElement(By.cssSelector("a[title=\"Img02.jpg\"] > img")).click();
    this.driver.findElement(By.id("saveProductImage")).click();
    this.driver.findElement(By.cssSelector("span.k-select > span.k-icon.k-i-arrow-s")).click();
    this.driver.findElement(By.xpath("//ul[@id='selectShippingTemplate_listbox']/li[2]")).click();
    this.driver.findElement(By.id("logisticsWeight_1367_1255")).click();
    this.driver.findElement(By.id("logisticsWeight_1367_1255")).clear();
    this.driver.findElement(By.id("logisticsWeight_1367_1255")).sendKeys("500");
    this.driver.findElement(By.xpath("(//input[@type='text'])[53]")).click();
    this.driver.findElement(By.id("logisticsWeight_1367_1542")).clear();
    this.driver.findElement(By.id("logisticsWeight_1367_1542")).sendKeys("1000");
    this.driver.findElement(By.id("logisticsWeight_1367_1371")).clear();
    this.driver.findElement(By.id("logisticsWeight_1367_1371")).sendKeys("1500");
    this.driver.findElement(By.id("logisticsWeight_1369_1255")).clear();
    this.driver.findElement(By.id("logisticsWeight_1369_1255")).sendKeys("2000");
    this.driver.findElement(By.xpath("(//input[@type='text'])[59]")).click();
    this.driver.findElement(By.id("logisticsWeight_1369_1542")).clear();
    this.driver.findElement(By.id("logisticsWeight_1369_1542")).sendKeys("2500");
    this.driver.findElement(By.id("logisticsWeight_1369_1371")).clear();
    this.driver.findElement(By.id("logisticsWeight_1369_1371")).sendKeys("3500");
    this.driver.findElement(By.xpath("(//input[@name='stockReduceType'])[2]")).click();
    this.driver.findElement(By.id("toEidtDetail")).click();
    this.driver.findElement(By.id("toAddSku")).click();
    this.driver.findElement(By.id("addSpecV_0")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div/span/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div[3]")).click();
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.linkText("+添加")).click();
    this.driver.findElement(By.xpath("//div[@id='skuValueWindow']/div/div/fieldset/div/div/span/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.xpath("//button[@onclick='addSkuValue();']")).click();
    this.driver.findElement(By.id("addSpec")).click();
    this.driver.findElement(By.xpath("(//button[@onclick='openSelSpecWindow(this);'])[2]")).click();
    this.driver.findElement(By.xpath("//div[@id='addSkuWindow']/div/div/fieldset/div/div/span/span/span/span")).click();
    this.driver.findElement(By.cssSelector("li.k-item.k-state-hover")).click();
    this.driver.findElement(By.id("toAddSku")).click();
    this.driver.findElement(By.xpath("(//button[@onclick='openSelSpecWindow(this);'])[2]")).click();
  }

}
